name: Auto Resize Images

on:
  push:
    paths:
      - "src/**"
  pull_request:

jobs:
  resize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install Pillow
      - name: Run resize script
        run: |
          python3 auto-resize.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Add edited photos"
          git push
